export const signup = "http://localhost:8080/crm/api/v1/auth/signup";
export const signin = "http://localhost:8080/crm/api/v1/auth/signin";
export const getAllUsers = "http://localhost:8080/crm/api/v1/users/";
export const userBasedonUserId = `http://localhost:8080/crm/api/v1/users/`;
export const updateUserInfo = `http://localhost:8080/crm/api/v1/users/`;
export const createNewTicket = "http://localhost:8080/crm/api/v1/tickets/";
export const getAllTickets = "http://localhost:8080/crm/api/v1/tickets/";
// export const getTicketsByStatus = `/crm/api/v1/tickets?status=${TicketStatus}`;
export const updateTicketById = `http://localhost:8080/crm/api/v1/tickets/`;
export const getAllComments = `http://localhost:8080/crm/api/v1/tickets/`;
// export const getTicketData = `/crm/api/v1/tickets/${ticketId}`;
// export const searchTicket = `/crm/api/v1/tickets/${id}`;
